[package]
name = "cirque"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
rustls = {version = "0.23", default-features = false, features = ["std"]}
rustls-pemfile = "2.1.2"
yaml-rust2 = "0.8.1"
