name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check
        run: |
          cargo clippy --all-features --all-targets
          cargo fmt --all -- --check
      - name: Build
        run: cargo build --release
      - name: Run tests
        run: cargo test
  miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          #cargo miri setup
      - name: Test with Miri
        run: cargo miri test
  cargo-deny:
    name: "cargo deny"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          rust-version: "1.80.0"
