name: Chirc-testsuite

on: [push, pull_request]


env:
  CARGO_TERM_COLOR: always
  UV_SYSTEM_PYTHON: 1
  FORCE_COLOR: 1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install pytest
      run: uv pip install pytest pytest-html pytest-json

    - name: test
      run: |
        python scripts/launch_tu.py
